# Generated by Django 4.0.6 on 2023-12-17 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostNfound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='claim',
            name='owner',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='contact',
            field=models.CharField(default='unknown', max_length=12),
        ),
        migrations.AlterField(
            model_name='claim',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 17)),
        ),
        migrations.AlterField(
            model_name='claim',
            name='email',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='contact',
            field=models.CharField(default='unknown', max_length=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 17)),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
