# Generated by Django 4.0.6 on 2023-12-17 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lostNfound', '0002_claim_description_claim_owner_alter_claim_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
