# Generated by Django 4.0.6 on 2023-12-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostNfound', '0003_alter_claim_date_alter_item_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='password',
            field=models.CharField(default='X', max_length=100),
        ),
    ]
