# Generated by Django 4.0.6 on 2023-12-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostNfound', '0005_remove_claim_item_claim_image_claim_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='keywords',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='name',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='keywords',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='claim',
            name='image',
            field=models.ImageField(default='default.png', max_length=1000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.png', max_length=1000, upload_to=''),
        ),
    ]
