# Generated by Django 4.0.6 on 2023-12-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostNfound', '0006_claim_keywords_claim_name_item_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.png', max_length=1000, upload_to='media/'),
        ),
    ]
