# Generated by Django 4.0.6 on 2023-12-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lostNfound', '0008_alter_claim_image_alter_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='unknown', max_length=100)),
                ('password', models.CharField(default='X', max_length=100)),
                ('contact', models.CharField(default='unknown', max_length=100)),
                ('image', models.TextField(default='default.png', max_length=1000)),
                ('address', models.TextField(default='unknown', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lostNfound.person'),
        ),
        migrations.AddField(
            model_name='item',
            name='person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lostNfound.person'),
        ),
    ]
