# Generated by Django 4.0.6 on 2023-12-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostNfound', '0009_person_claim_person_item_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default='unknown', max_length=1000),
        ),
    ]
