# Generated by Django 4.0.6 on 2023-12-19 20:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lostNfound', '0010_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='email',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='password',
        ),
        migrations.RemoveField(
            model_name='item',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='item',
            name='email',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='item',
            name='password',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', max_length=1000)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('criminal', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='crimes', to='lostNfound.person')),
                ('reportee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='lostNfound.person')),
            ],
        ),
    ]
